apiVersion: v1
kind: Service
metadata: 
  name: springboot-backend
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30006
  selector:
    app: backend-app